title: Raji Sobur Kewulere
logo: /assets/img/convo dp.jpg
description: Researcher|Machine Learning|AI Enthusiast|Data Analysis|Medical Image Analysis|IT Project Manager|Product Designer|Humanitarian
show_downloads: true
theme: jekyll-theme-minimal
